WVKBD_LAYOUT="mobintl"
WVKBD_FONT="JetBrains Mono 20"

# Color format: rrggbb
WVKBD_BG="282a36"
WVKBD_FG="44475a"
WVKBD_FG_SP="bd93f9"
WVKBD_PRESS="6272a4"
WVKBD_PRESS_SP="ff79c6"
WVKBD_TEXT="f8f8f2"
WVKBD_TEXT_SP="f8f8f2"

WVKBD_ALPHA="230"
WVKBD_ANCHOR="bottom"