[Appearance]
style=Fusion
color_scheme_path=/usr/share/qt5ct/colors/Dracula.conf
icon_theme=Dracula
standard_dialogs=default
font=Sans Serif,10,-1,5,50,0,0,0,0,0
fixed_font=Monospace,10,-1,5,50,0,0,0,0,0
